# This file was generated by GoReleaser. DO NOT EDIT.
cask "ec2-spot-interrupter" do
  name "ec2-spot-interrupter"
  desc "A simple CLI tool that triggers Amazon EC2 Spot Interruption Notifications and Rebalance Recommendations."
  homepage "https://github.com/aws/amazon-ec2-spot-interrupter"
  version "0.0.14"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ec2-spot-interrupter"

  on_macos do
    on_intel do
      url "https://github.com/aws/amazon-ec2-spot-interrupter/releases/download/v#{version}/ec2-spot-interrupter_darwin_amd64.tar.gz"
      sha256 "5d5fbb65c5abfe40d8a0fac21f46c46f32d16166f0c4f8d9ab542c0dd372c1db"
    end
    on_arm do
      url "https://github.com/aws/amazon-ec2-spot-interrupter/releases/download/v#{version}/ec2-spot-interrupter_darwin_arm64.tar.gz"
      sha256 "5650f1252692ddfd9adc09700eb4c2b8e2332c97adb034963fc9343c1629b6cc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/aws/amazon-ec2-spot-interrupter/releases/download/v#{version}/ec2-spot-interrupter_linux_amd64.tar.gz"
      sha256 "329622784a9b923054b74a3f2b3635ad274d4184a1da739ab12e901930f2c2ed"
    end
    on_arm do
      url "https://github.com/aws/amazon-ec2-spot-interrupter/releases/download/v#{version}/ec2-spot-interrupter_linux_arm64.tar.gz"
      sha256 "7da9fbfd6995fec4b25c5252b1a668d4acff5398e3fe005ad4b10d42df7548aa"
    end
  end

  caveats do
    "ec2-spot-interrupter --interactive"
  end

  # No zap stanza required
end
